### ISSUE TITLE
Trollbox wrong text submitted

### ISSUE THREAD

**Issue by juhanihaapala** [bitshares/beet#107]
**Describe the bug**
No matter what I wrote the message was always 'text'.

**To Reproduce**
1. Go to http://www.bitsharesvotes.com/
2. Click on trollbox
3. Wrote text
4. Submitted it

**Expected behavior**
The text that I wrote appear as new message 

**Actual behavior**
The text in new message was 'text' 

**Screenshots**
![image](https://user-images.githubusercontent.com/3079827/56274619-bd4b3a00-6107-11e9-82d7-0898fe75365b.png)

**Desktop (please complete the following information):**
 - OS: Ubunut 18.04
 - Browser: Chromium Browser
 - Version 73.0.3683.75

**Comment by clockworkgr** [comment]
bitsharesvotes requires a small update to work with the beta release,,,we should get round to it today @sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
Fixed

![image](https://user-images.githubusercontent.com/33128181/56277294-609a5000-6104-11e9-9971-167e86506870.png)
