### ISSUE TITLE
Sign a raw (already finalized) transaction

### ISSUE THREAD

**Issue by xeroc** [bitshares/beet#115]
**Is your feature request related to a problem? Please describe.**
I hava a raw transaction produced elsewhere and only want beet to add a signature.

**Describe the solution you'd like**
No solution, because Beet complains about the transaction being "already finalized".

This relates to: 
https://github.com/bitshares/bitsharesjs/issues/48

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/beet/pull/117
