### ISSUE TITLE
beet hackathon demo - After logging out manually . If  the authorization is done yet the vue js page does not detect it. Looks like state is not retained .

### ISSUE THREAD

**Issue by manikey123** [bitshares/beet#122]
![image](https://user-images.githubusercontent.com/22608398/57588697-ef647780-74cc-11e9-8aae-d52c6d99f773.png)

**Comment by manikey123** [comment]
please assign to me @sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
Can you describe the steps to reproduce?

**Comment by sschiessl-bcp** [comment]
Will you be actively following this?

**Comment by manikey123** [comment]
Closing this as this will be resolved part of #123
