### ISSUE TITLE
Allow Wallet to Hold Only the Memo Key of an Account

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/beet#128]
As a security focused Beet user I want to limit the types of private keys held in my wallets so that I may mitigate key management risks.

Currently the Beet Wallet requires the Active Authority of an account when importing keys. Leaving the field blank results in `Authority (active) is mandatory, but not given by user`. Please allow the user to supply only the Memo Key for a given account within the wallet.

Best practices for interacting with identity management services is to use the Memo Key to sign a message for authentication. Forcing a user to import their Active Key is an unnecessary requirement of the wallet for this use case.

**Comment by sschiessl-bcp** [comment]
Closed with #129
