### ISSUE TITLE
[mac] logo on dock differs from beet app logo

### ISSUE THREAD

**Issue by bitcoinsfacil** [bitshares/beet#131]
**Describe the bug**
The logo that appears on the dock for apple desktop app is different from the one on the application 
![Screen Shot 2019-06-27 at 13 10 55](https://user-images.githubusercontent.com/1756850/60261788-045e6400-98dd-11e9-833a-fecce5b6b1d0.png)

**Comment by sschiessl-bcp** [comment]
Thanks! That is actually the Electron icon.
