### ISSUE TITLE
Denial of Service (DoS)

### ISSUE THREAD

**Issue by larrycameron80** [bitshares/beet#138]
Denial of Service (DoS)
Vulnerable module: js-yaml
Introduced through: vueify@9.4.1
Detailed paths
Introduced through: beet@bitshares/beet#1df51a98ceeb4aae49dc804a2218b70363f43f42 › vueify@9.4.1 › cssnano@3.10.0 › postcss-svgo@2.1.6 › svgo@0.7.2 › js-yaml@3.7.0
Overview
js-yaml is a human-friendly data serialization language.

Affected versions of this package are vulnerable to Denial of Service (DoS). The parsing of a specially crafted YAML file may exhaust the system resources.

**Comment by clockworkgr** [comment]
Fixed via https://github.com/bitshares/beet/pull/141
