### ISSUE TITLE
Bitcoin import not possible

### ISSUE THREAD

**Issue by thontron** [bitshares/beet#145]
Selecting Bitcoin to import address/key and no option to import.

Mac 10.14.5

<img width="582" alt="Screen Shot 2020-03-02 at 9 21 14 AM" src="https://user-images.githubusercontent.com/33364996/75822045-46de1780-5d6d-11ea-9236-cbe529cf6bab.png">
<img width="590" alt="Screen Shot 2020-03-02 at 9 21 47 AM" src="https://user-images.githubusercontent.com/33364996/75822053-4cd3f880-5d6d-11ea-8284-aa631c3893e0.png">

**Comment by sschiessl-bcp** [comment]
Please retry when launching from develop branch
