### ISSUE TITLE
Beet domain updated to beet.bitshares.org

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/beet#164]
New domain is beet.bitshares.org -> 127.0.0.1

Premium Comodo/Positive SSL certificates valid for 1 year from the date of this post available:
[beet.tar.gz](https://github.com/bitshares/beet/files/6618797/beet.tar.gz)

**Comment by sschiessl-bcp** [comment]
Done with https://github.com/bitshares/beet/commit/9a8bc2534981ab17056d25ca8065faf3239105e0
