### ISSUE TITLE
Include Memo in the transfer for BitShares ($BTS)

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/beet#169]
Add feature of "Memo" to the Beet.

**Comment by sschiessl-bcp** [comment]
What do you mean, add?

It is available by specifying memo in the payload (https://github.com/beetapp/beet-examples/blob/2b035db7af33f87b6af43a8c174a6e8ab6cf3d65/bitshares/inject.html#L25)

**Comment by dls-cipher** [comment]
See, very retarded me. Can you provide then example to humble and ignorant me - how JSON memo would be done in that payload

{"type":"three_months"}

**Comment by grctest** [comment]
Reintroduced the memo field to the transfer prompt
https://github.com/bitshares/beet/pull/189

**Comment by grctest** [comment]
Now merged into the develop branch, can close issue now.
