### ISSUE TITLE
Bitshares explorer link (open-explorer) is down

### ISSUE THREAD

**Issue by grctest** [bitshares/beet#174]
**Describe the bug**
There is a dead HTML link within the Beet Bitshares interface.

**To Reproduce**
Login to beet bts wallet.
Click "click here" next to explorer, see dead website.

**Expected behavior**
Valid block explorer.

**Additional context**
There are other valid block explorers to use than the dead one.

**Comment by sschiessl-bcp** [comment]
Included now https://blocksights.info as a fork of open-explorer (https://github.com/blocksights/blocksights-open-explorer)

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/beet/commit/13d766e696bfa4a74a8b8a89c8813a40872d7e61
