### ISSUE TITLE
The smoke network is abandoned & dead - remove

### ISSUE THREAD

**Issue by grctest** [bitshares/beet#178]
**Describe the bug**
The smoke network was abandoned by its creators and witnesses, it's completely dead & its continued inclusion isn't needed.

**To Reproduce**
Try to access smoke.io see that it's dead.

**Expected behavior**
Smoke network isn't dead.

**Additional context**
RIP their DPOS chain

**Comment by abitmore** [comment]
@grctest can you please create a pull request? Thanks.

**Comment by sschiessl-bcp** [comment]
Done https://github.com/bitshares/beet/commit/2f15e9318182ed90715fe587f9b3c0775758891b

Deactivated other chains as well due to security issues with the libraries (would need maintenance) https://github.com/bitshares/beet/commit/13a6f4e3370fc0b948e0d1f13c08968a88ba4686
