### ISSUE TITLE
Support new Bitshares operations

### ISSUE THREAD

**Issue by grctest** [bitshares/beet#198]
**Is your feature request related to a problem? Please describe.**
New features have been introduced to Bitshares which haven't yet been tested/implemented in Beet yet.

Namely, Bitshares AMM and Bitshares credit offers.

**Describe the solution you'd like**
Support AMM and credit offer functionality in Beet so that new tools can take advantage of these new technologies.

**Describe alternatives you've considered**
Signing and broadcasting a custom operation, less readable than officially supporting these 2 new technologies.

Not using Beet for these Bitshares features.

**Additional context**
Supporting 100% of Bitshares capability should be one of our aims, to promote Bitshares.

**Comment by sschiessl-bcp** [comment]
Technically, they are supported via the generic request, or my injecting into TransactionBuilder. How would you want to support them more directly?

**Comment by grctest** [comment]
True they could already be signed & broadcast through existing popup prompts.

I was thinking of their potential addition to Bitshares visualize function https://github.com/bitshares/beet/blob/develop/src/lib/blockchains/BitShares.js#L1015

**Comment by grctest** [comment]
Supported further in https://github.com/bitshares/beet/pull/222
