### ISSUE TITLE
Optimize multi-operation prompts

### ISSUE THREAD

**Issue by grctest** [bitshares/beet#249]
**Is your feature request related to a problem? Please describe.**

When you create a prompt to transfer BTS to 50+ users, the current prompt logic iterates over each user, performing lookups for the recipient user & the token symbol.

Iterating in this manner for 50 accounts takes quite a while, and even began timing out.

**Describe the solution you'd like**

Cache recent asset symbol queries, so for example if you're airdropping the one asset to many users, you only do one asset symbol query rather than 50+

**Describe alternatives you've considered**

Avoid blockchain queries, only show the recipient account ID (instead of accountname) and the ID of the asset being sent. Doing so sacrifices end user security though, as they can't easily determine the details of the prompt they're looking at.

**Comment by sschiessl-bcp** [comment]
Caching is certainly a good way, on top of that we can introduce mass queries, i.e. query all 50 in one call

**Comment by grctest** [comment]
Accounts and assets which need to be fetched for multi-operation prompts are now fetched in batches, merged into develop branch.
