### ISSUE TITLE
Add automatic build process of binaries

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/beet#27]
Similar to the UI beet should be build automatically for tags on master branch. This is issue is to track progress on it.

The build process will be done by a separate github account made for that purpose @bitshares-ui-automation

**Comment by clockworkgr** [comment]
awesome...how does it work? :D

**Comment by sschiessl-bcp** [comment]
- Setup new github account for build processes: bitshares-ui-automation
- Link and configure it to Travis and AppVeyor
  - https://travis-ci.org/bitshares/beet
  - https://ci.appveyor.com/project/bitshares-ui-automation/beet
- Finalize and tweak build process
  - https://github.com/bitshares/beet/blob/develop/.travis.yml
Configuration automatically read by Travis
  - https://github.com/bitshares/beet/blob/develop/appveyor.yml
Configuration automatically read by AppVeyor
  - https://github.com/bitshares/beet/blob/develop/package.json
Adjusted `config.forge` and `scripts` (Warning: `install` script is automatically executed with `npm ci`, duh!)
  - https://github.com/bitshares/beet/blob/develop/package.sh
Script called by CI to make the project (build binaries)
  - https://github.com/bitshares/beet/blob/develop/publish.sh
Script called by CI to publish to GitHub. In order to achieve that the environment variable `GITHUB_TOKEN` is set, which is encrypted for Travis and AppVeyor (see `secure` entries in the respective configs)
  - https://github.com/bitshares/beet/blob/develop/write_digest.js
Script to create checksums, not completed will finalize with first real release
