### ISSUE TITLE
Beet load time

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/beet#29]
**Describe the bug**
Load time for the app was roughly 75 seconds.
After it loaded, it flashed, followed by another window.
Maybe not an error (assuming flash is seeking a wallet) but the load time is notable. 

**To Reproduce**
1. Downloaded, installed Beet. Reboot the system. See Gif for re-loading of Beet flash

**Expected behavior**
1) A faster load of the app
2) No flash with a second window.

- Windows OS 8.1
- Browser Opera
![beet_load_capture](https://user-images.githubusercontent.com/18186497/48661098-5af3ed80-ea32-11e8-906e-c956efe37811.gif)

**Comment by clockworkgr** [comment]
That's actually the (crappy) squirrel installer...need to find out how to package in a proper installer

**Comment by clockworkgr** [comment]
@sschiessl-bcp does reference wallet use squirrel or NSIS? maybe we should have a look at the electron-buidler config there

**Comment by sschiessl-bcp** [comment]
NSIS

**Comment by sschiessl-bcp** [comment]
https://www.npmjs.com/package/electron-forge-maker-nsis

Might work by simply installing this and replacing the config key.

**Comment by sschiessl-bcp** [comment]
Tried it too on Windows, it is horrible. Looks more like a virus than a serious app

**Comment by clockworkgr** [comment]
yeah...we need to do the NSIS one...even if it takes long...it looks ..."normal"

**Comment by TechsUsInc** [comment]
I booted Beet with Discord open.
Discord becomes unresponsive. 
Beet load time seems extended.

**Comment by clockworkgr** [comment]
closed in #37  (NSIS installer)
