### ISSUE TITLE
Min/Max/Close/tray behavior

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/beet#30]
**Describe the bug**
1. Multiple Beet icons in the tray after first opening of Beet.
2. Clicking the maximum button tabs from right to left; clicking max again tabs left to right.
3. Clicking the minimum button reduces to the tray without the running in the background notification.
4. Clicking the "X" reduces to the tray; does not close the program. User must go to the tray, right click on the Beet icon, click quit to quit the program.

**To Reproduce**
1. Open Beet
2. Click to open the tray noting multiple Beet icons
3. Open Beet; click maximum window noting tabulation to the left; click max again noting tabulation to 
    the right.
4. Click minimize window noting it reduces to the tray without the initial running in the background 
    notification.
5. Click the "X" to end and close Beet noting that it did not close, but minimized to the tray. Clicking on 
   the Beet icon in the tray merely re-opens the app. User must right mouse click on the Beet icon in the 
   tray then click quit to exit the app.

**Expected behavior**
1. Clicking maximum to maximize the window, not tab
2. Clicking minimum button to minimize to the taskbar; if reduced to the tray, a notification would help 
    inform the user.
3. Clicking the "X" to end and close Beet.

**Screenshots**
See Gif

**Desktop (please complete the following information):**
 - OS: 8.1
 - Browser Opera
![beet_window_capture](https://user-images.githubusercontent.com/18186497/48661413-e40d2380-ea36-11e8-942a-b1355ca60bbb.gif)

**Comment by clockworkgr** [comment]
Close button not quitting but reducing to tray is actually planned behaviour similar to other apps. You should be getting a notification about it upon first minimize/close.

Maximize not working properly is because beet is supposed to have fixed dimensions. I'll check electron documentation  , possibly removing the button altogether.

Multiple Icons, not so sure about. Does it happen on first run? Is it possible those icons are left over from running Beet previously and they're not unregistering themselves properly from the taskbar?

Thanks for the reports btw!

**Comment by clockworkgr** [comment]
Notification only appears on first minimise per run..

maybe switch to a popup notification with a "Don't show again" checkbox?

**Comment by TechsUsInc** [comment]
That's a great idea, a "Don't show again" checkbox.

Thinking more about the Max button not maximizing, or removing, it occurred to me that you may be able to solve two issues in one by repairing the maximize button;
1. The Max button would work as expected
2. The key input on Step 2 might reveal the entire key if the user is able to enlarge the screen. 
   IMO disabling the Max button and repairing the key input might be best in regards to mobile users experience.

**Comment by clockworkgr** [comment]
I  need to fix these as part of the redesign.. Will make it run frameless and add close/minimise buttons in CSS along with "Don't show again" popup

**Comment by clockworkgr** [comment]
closed in #37
