### ISSUE TITLE
Step 2: key input; tooltips; Copy/paste

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/beet#31]
**Describe the bug**
1. Active/Memo key input exceeds the window size; consider reducing the font size or enlarging the key 
   input window size so that the keys fit within the window in entirety. 
2. Unable to copy/paste the keys
3. Tooltips are generic; Consider detailed, simple directive tooltips to guide the user 

**To Reproduce**
1. Open Beet; Go to step 2 for Active/Memo key input
2. Click in Active key window; attempt to copy/paste the key into the window
3. Note that copy/paste is disabled; Input the Active key manually noting it scrolls outside the window
![beet2_key_capture_2](https://user-images.githubusercontent.com/18186497/48661821-c3949780-ea3d-11e8-9dda-9206a48cb027.JPG)

4. Click in the Memo key window; attempt to copy/paste the key into the window
5. Note that copy/paste is disabled; Input the Memo key manually noting it scrolls outside of the window
6. Note that tooltips throughout are generic in terms of direction to the user

**Expected behavior**
1. Ability to copy/paste the key; if disabled, consider a copy/paste disabled notification to the user
2. Ability to input the Active/Memo key and see it in entirety.
3. Ability to hover over a field, utilizing the tooltip for concise, direction.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera

**Additional context**
Best practice is never copy/paste keys, but eliminates human error entry. 
Tooltip wording is crucial for the user to know exactly what is asked of them, especially when it involves keys.

**Comment by clockworkgr** [comment]
Copy/Paste should not be disabled..(and are not on mine) I'll see if i can reproduce.

Rest of the UX stuff.... You're absolutely right but I haven't even began on UX stuff as it is subject to change once branding/color schemes/fonts etc are decided

**Comment by g3d** [comment]
:+1: for copy paste, was able to reproduce on latest release (0.3.4)

**Comment by clockworkgr** [comment]
@TechsUsInc  & @g3d  are you guys on OS X?

**Comment by clockworkgr** [comment]
OS X def has this issue and I'll put up a new release fixing it.

Not sure what's wrong with @TechsUsInc 's report which is on windows and SHOULD work (def works on Win10)

Looking into it

**Comment by g3d** [comment]
@clockworkgr yep, it was reproduced on OSX `10.14.3` (Darwin Kernel Version `18.2.0`)

**Comment by TechsUsInc** [comment]
> OS X def has this issue and I'll put up a new release fixing it.
> 
> Not sure what's wrong with @TechsUsInc 's report which is on windows and SHOULD work (def works on Win10)
> 
> Looking into it

Win 8.1

**Comment by clockworkgr** [comment]
Should be fixed in https://github.com/bitshares/beet/pull/63
