### ISSUE TITLE
Step 2: Checkbox for .BIN import

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/beet#33]
**Is your feature request related to a problem? Please describe.**
Consider a Local Wallet check box on Step 2 allowing .BIN import from a back up or storage device.

**Describe the solution you'd like**
Ability to utilize Beet for both local and cloud wallet users.

**Comment by clockworkgr** [comment]
Duplicate. Already in the pipeline: see https://github.com/bitshares/beet/issues/11
