### ISSUE TITLE
[15] Beet UX/UI Design

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/beet#34]
The UI design will be handled by the winner of the Beet logo contest (https://whaleshares.io/art/@pixel/beet-artcontest-bring-life-to-beet)

Beet UX is bootstrap based.

This is a list of things we're going to need:

- [ ] Primary logo with & without app name
- [ ] Logo in secondary color scheme with & without app name
- [ ] Mini logo/icon
- [ ] Main font
- [ ] Secondary/Headings font
- [ ] Button style 
- [ ] Bootstrap theme colors x 8 (primary,secondary,success,danger, warning, info, light,dark )
- [ ] Form control styles (input textbox, checkbox, radio, switch)
- [ ] Status indicator (connected/not connected)
- [ ] Icon set suggestion (close, lock/unlock, save, load etc.)
- [ ] Modal/popup styling

**Comment by clockworkgr** [comment]
@sschiessl-bcp  am I missing anything?

**Comment by clockworkgr** [comment]
@podanrj has done an awesome job.

@sschiessl-bcp have a look as well and tell me what you think

[beet_brand.pdf](https://github.com/bitshares/beet/files/2614234/beet_brand.pdf)
[brand_guide.pdf](https://github.com/bitshares/beet/files/2614235/brand_guide.pdf)

**Comment by sschiessl-bcp** [comment]
This looks fantastic @podanrj . 

Does it by any chance also fall within your expertise to create the CSS for it?

**Comment by podanrj** [comment]
No. :)
I don't understand CSS

**Comment by podanrj** [comment]
I work on with XD, some time i just send XD file to the DEV. :)

**Comment by clockworkgr** [comment]
@sschiessl-bcp falls within mine so dont worry :)

**Comment by clockworkgr** [comment]
@podanrj claimed 15hrs for his work.

I'm perfectly fine with that considering the standard of work produced and seeing as we',re now sorted in terms of style guide for the future. 

@startailcoon , @sschiessl-bcp you guys ok with that?

**Comment by clockworkgr** [comment]
ok...will add reference to UI repo
