### ISSUE TITLE
Error in add account screen

### ISSUE THREAD

**Issue by scientistnik** [bitshares/beet#6]
start app -> write name wallet -> write account name and keys -> this error:

![screenshot from 2018-08-27 12-48-05](https://user-images.githubusercontent.com/3358263/44653518-ab414d80-a9f7-11e8-8a95-14d51314847b.png)
![screenshot from 2018-08-27 12-47-39](https://user-images.githubusercontent.com/3358263/44653528-b1cfc500-a9f7-11e8-8c93-7b8f0abac22b.png)

**Comment by clockworkgr** [comment]
node is back up so should work ok. let me know so I can close this for now

**Comment by clockworkgr** [comment]
Closing this due to no further response for 4 days and a known issue/solution.

Will be fixed by #13
