### ISSUE TITLE
Cannot copy-paste private keys on beet

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/beet#61]
**Describe the bug**
Cannot copy-paste my private keys into beet app.  

Looks like hotkeys doesn't work when cursor is inside fields. I cannot even copy my username using cmd+a (after I typed it manually)

**Desktop (please complete the following information):**
 - OS: OSX (.dmg)
 - Beet 0.4.2

**Comment by clockworkgr** [comment]
Duplicate https://github.com/bitshares/beet/issues/31
