### ISSUE TITLE
Signed Message Format

### ISSUE THREAD

**Issue by xeroc** [bitshares/beet#81]
**Describe the bug**
The signed message from beet is awkward. It appears to be key, value pairs, but really is not:

    ["from", "xeroc", "BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE", "time", "Fri, 29 Mar 2019 12:12:43 GMT", "text", "Login at bitshares.org on 2019/03/29 @ 12:12:40 UTC"]

The additional pubkey has no `name`.

**To Reproduce**
use the example in `examples`.

**Expected behavior**
I want the array to declare a name for the public key. E.g.

* from: xeroc
* pubkey: BTS....
* ...

**Additional context**
Additionally, I believe that timestamps are easier to parse than human readable strings. Ultimately, no one will probably ever look into those messages anyways.

My particular use case is for login into a website using beet's signed message.

**Comment by clockworkgr** [comment]
JS has no concept of associative arrays.

Arrays have a guaranteed order.
Object properties order is NOT deterministic.

Therefore verification would break unless we could guarantee order of items in string representation of message container.

**Comment by xeroc** [comment]
Culprit here: https://github.com/bitshares/beet/blob/8bf3e740ab68e7731782afc773abb231e37002fb/src/lib/blockchains/BlockchainAPI.js#L59-L67

should read
```js
            let message = JSON.stringify([
                "from",
                accountName,
                "key",                                             // NEW !!!!!!!!!!!!!!
                this.getPublicKey(key),
                "time",
                new Date().toUTCString(),
                "text",
                randomString
]);
```

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bsips/issues/158
