### ISSUE TITLE
Refine download backup

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/beet#84]
- currently does not work 
![image](https://user-images.githubusercontent.com/33128181/55472895-835d3c80-560d-11e9-9ba8-6eb0ef7da8a1.png)
- filename should be `beet_<wallet name>_<timestamp>.json`

**Comment by clockworkgr** [comment]
oh my bad....thought i'd cleared this....it's not supposed to work yet...meant to empty the settings panel for this PR

**Comment by clockworkgr** [comment]
To be closed in https://github.com/bitshares/beet/pull/99
