### ISSUE TITLE
Add proper origin

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/beet#88]
aka website that the app is running under
![image](https://user-images.githubusercontent.com/33128181/55547578-de586780-56d1-11e9-89c8-c5a5a5b47ce7.png)

**Comment by clockworkgr** [comment]
Beet is accessed via localhost.. It has no "real" origin knowledge apart from what beet-js tells it.

Beet-js sets the origin to the appName when served via localhost or file (no web server).

See here: https://github.com/bitshares/beet-js/blob/master/src/lib/BeetApp.js#L11-L16

**Comment by sschiessl-bcp** [comment]
Can we have ''localhost'' or "file" then instead? Having the app name twice looks stupid

**Comment by clockworkgr** [comment]
> Can we have ''localhost'' or "localfile" then instead? Having the app name twice looks stupid

only devs will see it...is it really that important?

just PR it in beet-js if you really want to :)
