### ISSUE TITLE
Broadcast successfull notification

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/beet#89]
I imagine a popover on the bottom above the footer saying

```
Transaction <type> successfully broadcast
<link to explorer>
```

That disappears after 5 seconds

**Comment by clockworkgr** [comment]
ok...we can use the existing alert system for that...

Blockchain APIs should build the appropriate link

**Comment by clockworkgr** [comment]
Closing this for now (simple notifications done in https://github.com/bitshares/beet/pull/103)

Will open a new one post beta with tx links (needs more work due to different result object formats).
