### ISSUE TITLE
Planned Development #3: Implement origin verification and authorisation persistence

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/beet#9]
When an app connects to Beet for the first time , it does so over an unencypted method call.

Upon connection, client lib provides a unique PIN visible to the user in the browser/app as well as in the Approval of connection request inside Beet. 

User must verify the same PIN is visible prior to approving as well as choose an account (see #10 ) to use with the app. Once approved, client lib and Beet proceed to a key exchange and use a HOTP implementation to identify all subsequent requests & responses.

**Comment by clockworkgr** [comment]
HOTP implementation:
https://github.com/hectorm/otpauth

**Comment by clockworkgr** [comment]
Whitelisting apps/actions background research:
https://medium.com/@nsjames/get-out-of-my-way-blockchain-7cd4383f4146

**Comment by sschiessl-bcp** [comment]
That's [Custom active permissions](https://github.com/bitshares/bsips/blob/master/bsip-0040.md) integration in Scatter, and we are taking it one step further! Like it

**Comment by clockworkgr** [comment]
Estimate for this as described on the PR changelog + relevant changes on beet-js (https://github.com/bitshares/beet-js/pull/2) is 25 hrs.

**Comment by sschiessl-bcp** [comment]
By estimation you mean it took you 25 hours as this is already completed, correct?

**Comment by clockworkgr** [comment]
Well..It actually took more...I mean that's what I estimate it should've taken assuming I was able to work on it properly focused and not in small spurts due to limited time availability.

Bar any bugs or whatever the code review comes up with, yes, this is completed.
